# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: server
before:
  hooks: ~
    # You may remove this if you don't use go modules.
  #- go mod download
builds:
  -
    id: server
    main: ./cmd/server
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: true
  name_template: "Release v{{.Version}}"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    ids:
      - server
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    dockerfile: Dockerfile.releaser
    image_templates:
      - "libsv/payd:latest"
      - "libsv/payd:{{.Version}}"
    extra_files:
      - data/sqlite/migrations/
