version: "3.7"

services:
  payd:
    container_name: payd
    image: local.payd
    environment:
      LOG_LEVEL: "info"
      DPP_HOST: "wss://faucet.bitcoinsv.io/dpp/ws"
      MAPI_CALLBACK_HOST: "http://faucet.bitcoinsv.io/dpp"
      PEERCHANNELS_HOST: 'faucet.bitcoinsv.io/peerchannels'
      WALLET_SPVREQUIRED: 'false'
    volumes:
      - ./run/regtest/payd:/paydb

  payd-merchant:
    container_name: payd-merchant
    image: local.payd
    volumes:
      - ./run/regtest/payd-merchant:/paydb

