version: "3.7"

services:
  payd:
    container_name: payd
    image: libsv/payd:0.1.13
    environment:
      DB_DSN: "file:paydb/wallet.db?_foreign_keys=true&pooling=true"
      LOG_LEVEL: "info"
      DPP_HOST: "wss://infra.bitcoinsv.io/dpp/ws"
      MAPI_CALLBACK_HOST: "http://infra.bitcoinsv.io/dpp"
      MAPI_MINERURL: "https://mapi.taal.com"
      MAPI_TOKEN: "Bearer testnet_27986b25bffa600482251a19e984f04d"
      MAPI_MINERNAME: "taal"
      PEERCHANNELS_HOST: "infra.bitcoinsv.io"
      PEERCHANNELS_PATH: "peerchannels"
      PEERCHANNELS_TLS: 'true'
      WALLET_SPVREQUIRED: 'false'
    volumes:
      - ./run/regtest/payd:/paydb

  payd-merchant:
    container_name: payd-merchant
    image: libsv/payd:0.1.13
    volumes:
      - ./run/regtest/payd-merchant:/paydb

