// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/libsv/payd"
	"sync"
)

// Ensure, that DestinationsReaderWriterMock does implement payd.DestinationsReaderWriter.
// If this is not the case, regenerate this file with moq.
var _ payd.DestinationsReaderWriter = &DestinationsReaderWriterMock{}

// DestinationsReaderWriterMock is a mock implementation of payd.DestinationsReaderWriter.
//
// 	func TestSomethingThatUsesDestinationsReaderWriter(t *testing.T) {
//
// 		// make and configure a mocked payd.DestinationsReaderWriter
// 		mockedDestinationsReaderWriter := &DestinationsReaderWriterMock{
// 			DestinationsFunc: func(ctx context.Context, args payd.DestinationsArgs) ([]payd.Output, error) {
// 				panic("mock out the Destinations method")
// 			},
// 			DestinationsCreateFunc: func(ctx context.Context, args payd.DestinationsCreateArgs, req []payd.DestinationCreate) ([]payd.Output, error) {
// 				panic("mock out the DestinationsCreate method")
// 			},
// 		}
//
// 		// use mockedDestinationsReaderWriter in code that requires payd.DestinationsReaderWriter
// 		// and then make assertions.
//
// 	}
type DestinationsReaderWriterMock struct {
	// DestinationsFunc mocks the Destinations method.
	DestinationsFunc func(ctx context.Context, args payd.DestinationsArgs) ([]payd.Output, error)

	// DestinationsCreateFunc mocks the DestinationsCreate method.
	DestinationsCreateFunc func(ctx context.Context, args payd.DestinationsCreateArgs, req []payd.DestinationCreate) ([]payd.Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// Destinations holds details about calls to the Destinations method.
		Destinations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args payd.DestinationsArgs
		}
		// DestinationsCreate holds details about calls to the DestinationsCreate method.
		DestinationsCreate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args payd.DestinationsCreateArgs
			// Req is the req argument value.
			Req []payd.DestinationCreate
		}
	}
	lockDestinations       sync.RWMutex
	lockDestinationsCreate sync.RWMutex
}

// Destinations calls DestinationsFunc.
func (mock *DestinationsReaderWriterMock) Destinations(ctx context.Context, args payd.DestinationsArgs) ([]payd.Output, error) {
	if mock.DestinationsFunc == nil {
		panic("DestinationsReaderWriterMock.DestinationsFunc: method is nil but DestinationsReaderWriter.Destinations was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args payd.DestinationsArgs
	}{
		Ctx:  ctx,
		Args: args,
	}
	mock.lockDestinations.Lock()
	mock.calls.Destinations = append(mock.calls.Destinations, callInfo)
	mock.lockDestinations.Unlock()
	return mock.DestinationsFunc(ctx, args)
}

// DestinationsCalls gets all the calls that were made to Destinations.
// Check the length with:
//     len(mockedDestinationsReaderWriter.DestinationsCalls())
func (mock *DestinationsReaderWriterMock) DestinationsCalls() []struct {
	Ctx  context.Context
	Args payd.DestinationsArgs
} {
	var calls []struct {
		Ctx  context.Context
		Args payd.DestinationsArgs
	}
	mock.lockDestinations.RLock()
	calls = mock.calls.Destinations
	mock.lockDestinations.RUnlock()
	return calls
}

// DestinationsCreate calls DestinationsCreateFunc.
func (mock *DestinationsReaderWriterMock) DestinationsCreate(ctx context.Context, args payd.DestinationsCreateArgs, req []payd.DestinationCreate) ([]payd.Output, error) {
	if mock.DestinationsCreateFunc == nil {
		panic("DestinationsReaderWriterMock.DestinationsCreateFunc: method is nil but DestinationsReaderWriter.DestinationsCreate was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args payd.DestinationsCreateArgs
		Req  []payd.DestinationCreate
	}{
		Ctx:  ctx,
		Args: args,
		Req:  req,
	}
	mock.lockDestinationsCreate.Lock()
	mock.calls.DestinationsCreate = append(mock.calls.DestinationsCreate, callInfo)
	mock.lockDestinationsCreate.Unlock()
	return mock.DestinationsCreateFunc(ctx, args, req)
}

// DestinationsCreateCalls gets all the calls that were made to DestinationsCreate.
// Check the length with:
//     len(mockedDestinationsReaderWriter.DestinationsCreateCalls())
func (mock *DestinationsReaderWriterMock) DestinationsCreateCalls() []struct {
	Ctx  context.Context
	Args payd.DestinationsCreateArgs
	Req  []payd.DestinationCreate
} {
	var calls []struct {
		Ctx  context.Context
		Args payd.DestinationsCreateArgs
		Req  []payd.DestinationCreate
	}
	mock.lockDestinationsCreate.RLock()
	calls = mock.calls.DestinationsCreate
	mock.lockDestinationsCreate.RUnlock()
	return calls
}
