// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/libsv/go-dpp"
	"github.com/libsv/payd"
	"github.com/libsv/payd/data/http"
)

// Ensure, that DPPMock does implement http.DPP.
// If this is not the case, regenerate this file with moq.
var _ http.DPP = &DPPMock{}

// DPPMock is a mock implementation of http.DPP.
//
// 	func TestSomethingThatUsesDPP(t *testing.T) {
//
// 		// make and configure a mocked http.DPP
// 		mockedDPP := &DPPMock{
// 			PaymentRequestFunc: func(ctx context.Context, req payd.PayRequest) (*dpp.PaymentRequest, error) {
// 				panic("mock out the PaymentRequest method")
// 			},
// 			PaymentSendFunc: func(ctx context.Context, args payd.PayRequest, req dpp.Payment) (*dpp.PaymentACK, error) {
// 				panic("mock out the PaymentSend method")
// 			},
// 		}
//
// 		// use mockedDPP in code that requires http.DPP
// 		// and then make assertions.
//
// 	}
type DPPMock struct {
	// PaymentRequestFunc mocks the PaymentRequest method.
	PaymentRequestFunc func(ctx context.Context, req payd.PayRequest) (*dpp.PaymentRequest, error)

	// PaymentSendFunc mocks the PaymentSend method.
	PaymentSendFunc func(ctx context.Context, args payd.PayRequest, req dpp.Payment) (*dpp.PaymentACK, error)

	// calls tracks calls to the methods.
	calls struct {
		// PaymentRequest holds details about calls to the PaymentRequest method.
		PaymentRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req payd.PayRequest
		}
		// PaymentSend holds details about calls to the PaymentSend method.
		PaymentSend []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args payd.PayRequest
			// Req is the req argument value.
			Req dpp.Payment
		}
	}
	lockPaymentRequest sync.RWMutex
	lockPaymentSend    sync.RWMutex
}

// PaymentRequest calls PaymentRequestFunc.
func (mock *DPPMock) PaymentRequest(ctx context.Context, req payd.PayRequest) (*dpp.PaymentRequest, error) {
	if mock.PaymentRequestFunc == nil {
		panic("DPPMock.PaymentRequestFunc: method is nil but DPP.PaymentRequest was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req payd.PayRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockPaymentRequest.Lock()
	mock.calls.PaymentRequest = append(mock.calls.PaymentRequest, callInfo)
	mock.lockPaymentRequest.Unlock()
	return mock.PaymentRequestFunc(ctx, req)
}

// PaymentRequestCalls gets all the calls that were made to PaymentRequest.
// Check the length with:
//     len(mockedDPP.PaymentRequestCalls())
func (mock *DPPMock) PaymentRequestCalls() []struct {
	Ctx context.Context
	Req payd.PayRequest
} {
	var calls []struct {
		Ctx context.Context
		Req payd.PayRequest
	}
	mock.lockPaymentRequest.RLock()
	calls = mock.calls.PaymentRequest
	mock.lockPaymentRequest.RUnlock()
	return calls
}

// PaymentSend calls PaymentSendFunc.
func (mock *DPPMock) PaymentSend(ctx context.Context, args payd.PayRequest, req dpp.Payment) (*dpp.PaymentACK, error) {
	if mock.PaymentSendFunc == nil {
		panic("DPPMock.PaymentSendFunc: method is nil but DPP.PaymentSend was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args payd.PayRequest
		Req  dpp.Payment
	}{
		Ctx:  ctx,
		Args: args,
		Req:  req,
	}
	mock.lockPaymentSend.Lock()
	mock.calls.PaymentSend = append(mock.calls.PaymentSend, callInfo)
	mock.lockPaymentSend.Unlock()
	return mock.PaymentSendFunc(ctx, args, req)
}

// PaymentSendCalls gets all the calls that were made to PaymentSend.
// Check the length with:
//     len(mockedDPP.PaymentSendCalls())
func (mock *DPPMock) PaymentSendCalls() []struct {
	Ctx  context.Context
	Args payd.PayRequest
	Req  dpp.Payment
} {
	var calls []struct {
		Ctx  context.Context
		Args payd.PayRequest
		Req  dpp.Payment
	}
	mock.lockPaymentSend.RLock()
	calls = mock.calls.PaymentSend
	mock.lockPaymentSend.RUnlock()
	return calls
}
