// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/libsv/go-bt/v2"
	"github.com/libsv/payd"
)

// Ensure, that FeeQuoteFetcherMock does implement payd.FeeQuoteFetcher.
// If this is not the case, regenerate this file with moq.
var _ payd.FeeQuoteFetcher = &FeeQuoteFetcherMock{}

// FeeQuoteFetcherMock is a mock implementation of payd.FeeQuoteFetcher.
//
// 	func TestSomethingThatUsesFeeQuoteFetcher(t *testing.T) {
//
// 		// make and configure a mocked payd.FeeQuoteFetcher
// 		mockedFeeQuoteFetcher := &FeeQuoteFetcherMock{
// 			FeeQuoteFunc: func(ctx context.Context) (*bt.FeeQuote, error) {
// 				panic("mock out the FeeQuote method")
// 			},
// 		}
//
// 		// use mockedFeeQuoteFetcher in code that requires payd.FeeQuoteFetcher
// 		// and then make assertions.
//
// 	}
type FeeQuoteFetcherMock struct {
	// FeeQuoteFunc mocks the FeeQuote method.
	FeeQuoteFunc func(ctx context.Context) (*bt.FeeQuote, error)

	// calls tracks calls to the methods.
	calls struct {
		// FeeQuote holds details about calls to the FeeQuote method.
		FeeQuote []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockFeeQuote sync.RWMutex
}

// FeeQuote calls FeeQuoteFunc.
func (mock *FeeQuoteFetcherMock) FeeQuote(ctx context.Context) (*bt.FeeQuote, error) {
	if mock.FeeQuoteFunc == nil {
		panic("FeeQuoteFetcherMock.FeeQuoteFunc: method is nil but FeeQuoteFetcher.FeeQuote was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockFeeQuote.Lock()
	mock.calls.FeeQuote = append(mock.calls.FeeQuote, callInfo)
	mock.lockFeeQuote.Unlock()
	return mock.FeeQuoteFunc(ctx)
}

// FeeQuoteCalls gets all the calls that were made to FeeQuote.
// Check the length with:
//     len(mockedFeeQuoteFetcher.FeeQuoteCalls())
func (mock *FeeQuoteFetcherMock) FeeQuoteCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockFeeQuote.RLock()
	calls = mock.calls.FeeQuote
	mock.lockFeeQuote.RUnlock()
	return calls
}
