// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/libsv/payd"
	"sync"
)

// Ensure, that OwnerStoreMock does implement payd.OwnerStore.
// If this is not the case, regenerate this file with moq.
var _ payd.OwnerStore = &OwnerStoreMock{}

// OwnerStoreMock is a mock implementation of payd.OwnerStore.
//
// 	func TestSomethingThatUsesOwnerStore(t *testing.T) {
//
// 		// make and configure a mocked payd.OwnerStore
// 		mockedOwnerStore := &OwnerStoreMock{
// 			OwnerFunc: func(ctx context.Context) (*payd.User, error) {
// 				panic("mock out the Owner method")
// 			},
// 		}
//
// 		// use mockedOwnerStore in code that requires payd.OwnerStore
// 		// and then make assertions.
//
// 	}
type OwnerStoreMock struct {
	// OwnerFunc mocks the Owner method.
	OwnerFunc func(ctx context.Context) (*payd.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Owner holds details about calls to the Owner method.
		Owner []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockOwner sync.RWMutex
}

// Owner calls OwnerFunc.
func (mock *OwnerStoreMock) Owner(ctx context.Context) (*payd.User, error) {
	if mock.OwnerFunc == nil {
		panic("OwnerStoreMock.OwnerFunc: method is nil but OwnerStore.Owner was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockOwner.Lock()
	mock.calls.Owner = append(mock.calls.Owner, callInfo)
	mock.lockOwner.Unlock()
	return mock.OwnerFunc(ctx)
}

// OwnerCalls gets all the calls that were made to Owner.
// Check the length with:
//     len(mockedOwnerStore.OwnerCalls())
func (mock *OwnerStoreMock) OwnerCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockOwner.RLock()
	calls = mock.calls.Owner
	mock.lockOwner.RUnlock()
	return calls
}
