name: Go

on:
  push:
    tags:
      - '*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.x,1.17.x]
        os: [macos-latest,ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
  build:
    strategy:
      matrix:
        go-version: [ 1.16.x,1.17.x ]
        os: [ macos-latest, ubuntu-latest ]
    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Tests
        run: make run-unit-tests
      - name: Build
        run: go build -v ./...
      - name: Generate Swagger
        if: startsWith(github.ref, 'refs/tags/')
        run: make install-swagger-gen && make generate-swagger
  release:
    needs: [golangci,build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}